# -*- coding: utf-8 -*-
"""SnowflakeandColabNotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3N6brpm_uyQSxbvK9OPKUgmN_DbrG1Q
"""

!pip install snowflake-connector-python

import snowflake.connector

# Establish a connection
conn = snowflake.connector.connect(
    user='RUMA1SINHA2',
    password='Planet@123',
    account='QQFDERZ-EM28086'
)

